// Action types

export const AUTH_TRUE = 'AUTH_TRUE';
export const AUTH_FALSE = 'AUTH_FALSE';

export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_TRUE = 'GET_PROFILE_TRUE';
export const GET_PROFILE_FALSE = 'GET_PROFILE_FALSE';

export const CHANGE_AVATAR_START = 'CHANGE_AVATAR_START';
export const CHANGE_AVATAR_TRUE = 'CHANGE_AVATAR_TRUE';
export const CHANGE_AVATAR_FALSE = 'CHANGE_AVATAR_FALSE';
